[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn --config gunicorn.conf.py app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11.8"
